### PR TITLE
update jsdom

### PR DESCRIPTION
**Pull request by qraynaud**
Here is the first PR of PR #16 split in 2.

### CODE REVIEW

**Comment by qraynaud** [comment]
Here is the first PR of PR #16 split in two.

**Comment by dai-shi** [comment]
The test passed. (but why?)

**Comment by qraynaud** [comment]
I don't understand your question.

**Comment by dai-shi** [comment]
We had an issue about testing when discussed in #16.
I cannot even reproduce the problem.

**Pull request merged**
