### PR TITLE
use a subprocess for isolation

### PR DESCRIPTION
**Pull request by qraynaud**
part 2 of PR #16 split in 2.

Be careful, since I move code around in this part, depending on which part you merge first, there is a need for a rewrite of the other to take into account the changes

### CODE REVIEW

**Comment by qraynaud** [comment]
ok, I'm working on the failed tests here…

**Comment by qraynaud** [comment]
ok, it was a simple race condition… it should be fixed now…

**Comment by dai-shi** [comment]
Hi, thanks for your work. I have a favor. Could you make it configurable? Maybe "useSubprocess" option.
I want the default behavior as it was before (single process). The memory leak issue is something that should be tackled later without using subprocess.

BTW, If we go with subprocess, PhantomJS is another option.

**Comment by qraynaud** [comment]
PhantomJS would work sure. But it would be a lot slower I think. I'm ok to go for an option.

I'll work on it ASAP.

**Comment by qraynaud** [comment]
I will close this one and I'll open a new one when everything will work properly on recent nodes.

**Pull request closed without merging**
